### ISSUE TITLE
Undefined is not a function - with-conditionals.js

### ISSUE THREAD

**Issue by fendyk** [marklawlor/nativewind#366]
**Describe the bug**
'Undefined is not a function', happens somewhere inside Nativewind's code. It comes out of the node_modules/nativewind/dist/runtime/native/styled/with-conditionals.js" file.

**To Reproduce**
Cannot show due to being a private application. I've used 2.0.0 before and everything seems to be working, but when I upgraded to 3.0.0, this happened.

**Expected behavior**
Should work after compilation and loading the application.

**Expo Snack**
It's a React Native app

**Screenshots**
![Scherm­afbeelding 2022-12-15 om 11 12 44](https://user-images.githubusercontent.com/56702979/207837957-ea6f5380-0b18-4457-8d0d-9269a4aa3d1a.png)

**Additional context**
For some reason, my Login page styling works but other wont. I have tried changing the 'content' in `tailwind.config.js` to different directories but it does not seem to help or dissolve the issue.

The issue even persists when I don't set a path at all in my `tailwind.config.js`.
`NativeWind: warn - No utility classes were detected in your source files. If this is unexpected, double-check the 'content' option in your Tailwind CSS configuration.`

**Comment by fendyk** [comment]
Update: I also have these weird warnings:

 `WARN  'new NativeEventEmitter()' was called with a non-null argument without the required 'addListener' method.
 WARN  'new NativeEventEmitter()' was called with a non-null argument without the required 'removeListeners' method.
 WARN  'new NativeEventEmitter()' was called with a non-null argument without the required 'addListener' method.
 WARN  'new NativeEventEmitter()' was called with a non-null argument without the required 'removeListeners' method.
 WARN  Require cycle: src/config/store.tsx -> src/models/index.ts -> src/models/measurementArchive.ts -> src/config/api.ts -> src/config/apiConfig.ts -> src/config/store.tsx`

**Comment by marklawlor** [comment]
This should be fixed in the v4 release
