### ISSUE TITLE
Type error with `className` on V4

### ISSUE THREAD

**Issue by axiomofjoy** [marklawlor/nativewind#833]
**Describe the bug**
When migrating from v2 to v4, I encountered a type issue when using `className` on a component.

I have a `SafeAreaView` component for Android that looks like this:

```
import { ReactNode, useMemo } from "react";
import { StatusBar, StyleProp, View, ViewStyle } from "react-native";

type SafeAreaViewProps = {
  children: ReactNode;
  style: StyleProp<ViewStyle>;
};
export default function SafeAreaView(props: SafeAreaViewProps) {
  const statusBarHeight = useMemo(() => StatusBar.currentHeight || 0, []);
  return (
    <View style={[props.style, { paddingTop: statusBarHeight }]}>
      {props.children}
    </View>
  );
}
```

I style the component with `className`:

```
<SafeAreaView className="flex-1 bg-slate-900">
```

This did not previously result in a type error, but it does on v4.

**Expected behavior**
I expect no type error to be raised.

**Comment by theblondealex** [comment]
Have you used the typescript guide to import the types?

https://www.nativewind.dev/v4/getting-started/typescript

**Comment by KundaiClay** [comment]
I also have the same issue with nativewind v4.  I am getting this error 
`   Property 'className' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<View> & Readonly<ViewProps>'.
  Overload 2 of 2, '(props: ViewProps, context: any): View', gave the following error.`

**Comment by theblondealex** [comment]
if you are using typescript as the guide states make sure to use a nativewind-env.d.ts file to import the className types

**Comment by marklawlor** [comment]
I cannot troubleshoot TypeScript issues with out a reproduction repo. TypeScript depends on your 
* codebase structure
* project dependencies
* possibly your global dependencies
* Editor/IDE settings

I'm going to close this issue and I cannot provide assistance when the only information provided is "it doesn't work for me"

Basic troubleshooting steps:
- Do you only get this error in your editor, or does `tsc` also produce the same error
- Do you get the same error in a brand new project

**Comment by kody435** [comment]
Still getting the same error

<img width="1335" alt="Screenshot 2024-09-06 at 09 21 36" src="https://github.com/user-attachments/assets/c2b6e58d-a705-4713-b426-96ebba053a3e">
