### ISSUE TITLE
v4: Next.js build error with nativewind 4.0.16

### ISSUE THREAD

**Issue by rpweb** [marklawlor/nativewind#673]
**Describe the bug**
Next.js app router is not working with nativewind `4.0.16`, whereas Next.js pages router does work.

**To Reproduce**
Forked from this issue https://github.com/marklawlor/nativewind/issues/635 and tried with app router instead of pages.
Here the fork: https://github.com/rpweb/example-nativewind-4-nextjs
run `yarn`, then `yarn dev` or `yarn build`

```
○ Compiling / ...
 ✓ Compiled / in 709ms (1215 modules)
 ⨯ node_modules/react-native-web/dist/cjs/modules/useLocale/index.js (23:59) @ defaultLocale
 ⨯ TypeError: (0 , _react.createContext) is not a function
    at __webpack_require__ (/Users/**/github/test/example-nativewind-4-nextjs/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/Users/**/github/test/example-nativewind-4-nextjs/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/Users/**/github/test/example-nativewind-4-nextjs/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/Users/**/github/test/example-nativewind-4-nextjs/.next/server/webpack-runtime.js:33:42)
    at RootLayout (./app/layout.tsx:16:78)
    at stringify (<anonymous>)
null
```

**Expected behavior**
No build error

**Screenshots**
![Screenshot 2023-11-24 at 19 24 01](https://github.com/marklawlor/nativewind/assets/7394465/31206977-30a1-464d-80a3-27e1eb629c84)

**Comment by marklawlor** [comment]
Following the stack trace you posted

` node_modules/react-native-web/dist/cjs/modules/useLocale/index.js (23:59) @ defaultLocale`

This is from React Native Web and refers to this line of code https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/modules/useLocale/index.js#L35

React Native Web is creating a context in the global scope, which is not allowed in Next.js's React Server Component implementation. This makes React Native Web incompatible with RSC and you should be raising the issue in their repo.

**Comment by marklawlor** [comment]
Related: https://github.com/necolas/react-native-web/discussions/2474

**Comment by rpweb** [comment]
Thank you for your help @marklawlor

**Comment by luixo** [comment]
> React Native Web is creating a context in the global scope, which is not allowed in Next.js's React Server Component implementation. This makes React Native Web incompatible with RSC and you should be raising the issue in their repo.

This error actually happens even if no RNW components are used in RSC code with Nativewind v4.

And as Next.js RSC approach is on the rise - I hope it could get addressed or at least warned about somewhere in the docs.

What actually happens:
- Any jsx is rendered in RSC code
- `jsxImportSource` is set to `nativewind` hence `react-native-css-interop`s jsx function runs
- it requires module `components` which imports `react-native` components to "tag" them with `className` prop(s).
- `react-native` is actually overriden by `react-native-web` which imports module `createElement` in a first line
- `createElement` module imports `LocaleProvider` from `useLocale` module
- `useLocale` module imports `createContext` from `React` which does not exist in RSC environment

I suspect that `react-native-web` maintainers will respond "just don't import react-native in server components" on this and that does sound reasonable.

It could be that workaround can be tailored to make a little bit more smart tagging function that will tag only react-native components whenever they are actually called (though to verify that, one has to import `react-native` which crashes the app - any ideas how to verify it otherwise?).
The very least I could do was to skip the whole tagging process if incoming `type` is a string - to let me render the minimal html wrapper.

**Comment by luixo** [comment]
@marklawlor 
I want to reiterate on that problem as half a year after it arose nothing changed.
There's no way to use RSCs with `nativewind` components while it imports `react-native`.
