### ISSUE TITLE
Styles are not applied on expo-web

### ISSUE THREAD

**Issue by suchcodemuchwow** [marklawlor/nativewind#154]
**Describe the bug**
Classnames are applied to html elements however they have no effect on style. I believe it's related with some versioning. It started to be unavailable after I upgraded couple of packages probably these ones: 
```json
    "expo": "^46.0.0",
    "react-native-web": "~0.18.7"
```

**To Reproduce**
I have created a simple repo which I try to change bg color to green which doesn't work.
https://github.com/suchcodemuchwow/nativewind-error
I have run this command:
`expo start --web --https --clear` 

**Expected behavior**
Styles are applied visually.

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.
https://snack.expo.dev/@git/github.com/suchcodemuchwow/nativewind-error

**Screenshots**

**Additional context**

**Comment by marklawlor** [comment]
You are using RNW `0.18`, so NativeWind switches to CSS. You will need to generate your `.css` using Tailwind CLI and import it like a normal web project.

**Comment by marklawlor** [comment]
Alternatively you can change back to the previous behaviour, but CSS offers more features and better performance.

https://www.nativewind.dev/quick-starts/expo#expo-sdk-45

**Comment by suchcodemuchwow** [comment]
Could you please point me in the right docs section to generating css and
importing it or provide an example ? I couldn’t find unfortunately.

**Comment by marklawlor** [comment]
For RNW 0.18, NativeWind is just a compatibility layer around Tailwind CSS. You need to follow normal Tailwind CSS installation.

https://tailwindcss.com/docs/installation

**Comment by mattwigham** [comment]
I just ran into the same issue and could use a bit more guidance as well re the normal Tailwind installation for web. I'm using Expo Web without a framework, so there are currently no CSS files or web-only layouts, so I'm not quite sure how to drop in the Tailwind CSS directives, and also unsure if this means I'd need to manually run the Tailwind CLI build watch every time. I think I'm just missing some understanding, thanks (and amazing lib @marklawlor).

**Comment by marklawlor** [comment]
On the web, NativeWind is just a compatibility layer between Tailwind CSS and React Native. NativeWind doesn't do any processing, it just makes React Native understand the `className` prop.

Expo Web without a framework is simply a web project using Webpack. So you can follow [Tailwind CSS PostCSS guide guide](https://tailwindcss.com/docs/installation/using-postcss) to install it as a PostCSS plugin in your webpack config.

**Comment by marklawlor** [comment]
The [Expo docs](https://www.nativewind.dev/quick-starts/expo#example-webpack-setup) and the example in the repo have been updated

**Comment by mattwigham** [comment]
Thanks for the help @marklawlor. Unfortunately I'm still not able to get things working on the web. 

When I run through the [Expo directions](https://www.nativewind.dev/quick-starts/expo) my app renders but with no styles applied on the web. 

When I run through the [PostCSS directions](https://www.nativewind.dev/guides/postcss), my `tailwind.config.js` errors saying `TypeError: nativewind is not a function`. 

When I tweak the `tailwind.config.js` be `plugins: [require("nativewind/tailwind/css")]` instead, I get `Module not found: Can't resolve './nativewind-output'`. 

Combinations of all the instructions haven't yielded anything either. Here's the relevant parts of my current code:

### package.json dependencies
```
{
  "nativewind": "^2.0.0-next.61",
  "postcss": "^8.4.16",
  "tailwindcss": "^3.1.8"
}
```

### tailwind.config.js
```
const nativewind = require("nativewind/tailwind/css");

module.exports = {
  content: ["./app/**/*.js"],
  theme: {
    extend: {},
  },
  plugins: [nativewind()],
};
```

### postcss.config.js
```
module.exports = {
  plugins: [require("tailwindcss"), [require("nativewind/postcss")]],
};
```

### webpack.config.js
```
const path = require("path");
const createExpoWebpackConfigAsync = require("@expo/webpack-config");

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(
    {
      ...env,
      babel: {
        dangerouslyAddModulePathsToTranspile: ["nativewind"],
      },
    },
    argv
  );

  config.module.rules.push({
    test: /\.css$/i,
    use: ["postcss-loader"],
  });

  return config;
};
```

### App.js
```
import "./nativewind-output";
```

I'm sure it's something dumb I'm doing, but any nudge in the right direction would be a huge help. A starter / example showing PostCSS and/or Expo Web working with NW 2.0 would be even better. Thanks again.

**Comment by marklawlor** [comment]
> the example in the repo have been updated

@mattwigham Please see the expo project in the examples folder.

**Comment by mattwigham** [comment]
Ahh, missed that. That fixed me up, I was definitely missing some things. Thanks so much @marklawlor. Congrats on 2.0.
